// State hub pages — one per US state with the highest healthcare-job
// density. Mirrors the specialty-hub pattern: each page ranks for
// "[state] healthcare jobs" and similar long-tail queries.

export type StateHub = {
  slug: string
  abbr: string             // 2-letter state code (matches public_jobs.state)
  name: string             // full state name
  metaDescription: string  // 150-160 chars
  shortDescription: string // for the page lede
  // Major employers / metros to mention in the page body for local relevance
  majorMetros: string[]
  topEmployers: string[]
}

export const STATE_HUBS: StateHub[] = [
  {
    slug: 'florida',
    abbr: 'FL',
    name: 'Florida',
    metaDescription: 'Free Florida healthcare jobs from verified employers — Tampa, Miami, Jacksonville, Orlando, Naples. Physician, NP, PA, RN, CRNA, and allied roles.',
    shortDescription: "Florida healthcare openings spanning the state's top systems — Tampa Bay, Miami-Dade, Jacksonville, Orlando, and Southwest Florida (Naples / Fort Myers).",
    majorMetros: ['Tampa', 'Miami', 'Jacksonville', 'Orlando', 'Naples', 'Fort Myers', 'Tallahassee'],
    topEmployers: ['Tampa General', 'AdventHealth', 'NCH Healthcare System', 'Lee Health', 'Mayo Clinic Florida', 'Baptist Health South Florida', 'Memorial Healthcare System', 'University of Miami Health'],
  },
  {
    slug: 'texas',
    abbr: 'TX',
    name: 'Texas',
    metaDescription: 'Free Texas healthcare jobs — Dallas, Houston, Austin, San Antonio. Physician, NP, PA, RN, CRNA roles from Houston Methodist, MD Anderson, UT Southwestern, more.',
    shortDescription: 'Texas healthcare openings across DFW, Houston, Austin, San Antonio, and the Rio Grande Valley.',
    majorMetros: ['Houston', 'Dallas', 'Fort Worth', 'Austin', 'San Antonio', 'El Paso', 'McAllen'],
    topEmployers: ['Houston Methodist', 'MD Anderson', 'UT Southwestern', 'Baylor Scott & White', 'HCA Healthcare', 'Memorial Hermann', 'Texas Health Resources', 'Cook Children\'s'],
  },
  {
    slug: 'california',
    abbr: 'CA',
    name: 'California',
    metaDescription: 'Free California healthcare jobs — LA, SF, San Diego, Sacramento. Physician, NP, PA, RN, CRNA roles from UCSF, Cedars-Sinai, Stanford, Kaiser, more.',
    shortDescription: 'California healthcare openings across LA, the Bay Area, San Diego, Sacramento, and Central Valley.',
    majorMetros: ['Los Angeles', 'San Francisco', 'San Diego', 'Sacramento', 'San Jose', 'Fresno', 'Long Beach'],
    topEmployers: ['UCSF Health', 'Cedars-Sinai', 'Stanford Health Care', 'Kaiser Permanente', 'UCLA Health', 'Sutter Health', 'Dignity Health', 'Scripps Health'],
  },
  {
    slug: 'new-york',
    abbr: 'NY',
    name: 'New York',
    metaDescription: 'Free New York healthcare jobs — NYC, Long Island, Westchester, Buffalo, Rochester. Physician, NP, PA, RN, CRNA roles from NYP, Mount Sinai, Northwell, more.',
    shortDescription: 'New York healthcare openings across NYC, Long Island, Hudson Valley, and upstate metros.',
    majorMetros: ['New York City', 'Buffalo', 'Rochester', 'Albany', 'Syracuse', 'Long Island', 'Westchester'],
    topEmployers: ['NewYork-Presbyterian', 'Mount Sinai Health System', 'Northwell Health', 'NYU Langone', 'Memorial Sloan Kettering', 'Hospital for Special Surgery', 'University of Rochester'],
  },
  {
    slug: 'illinois',
    abbr: 'IL',
    name: 'Illinois',
    metaDescription: 'Free Illinois healthcare jobs — Chicago, suburbs, Springfield. Physician, NP, PA, RN, CRNA roles from Northwestern, Rush, UChicago, Advocate, more.',
    shortDescription: 'Illinois healthcare openings across Chicagoland, the suburbs, and downstate.',
    majorMetros: ['Chicago', 'Aurora', 'Joliet', 'Naperville', 'Rockford', 'Springfield', 'Peoria'],
    topEmployers: ['Northwestern Medicine', 'Rush University Medical Center', 'UChicago Medicine', 'Advocate Aurora Health', 'NorthShore University HealthSystem', 'Loyola Medicine'],
  },
  {
    slug: 'pennsylvania',
    abbr: 'PA',
    name: 'Pennsylvania',
    metaDescription: 'Free Pennsylvania healthcare jobs — Philadelphia, Pittsburgh, Harrisburg. Physician, NP, PA, RN, CRNA roles from UPMC, Penn Medicine, Geisinger, more.',
    shortDescription: 'Pennsylvania healthcare openings across Philadelphia, Pittsburgh, Lehigh Valley, and central PA.',
    majorMetros: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Harrisburg', 'Erie', 'Reading', 'Scranton'],
    topEmployers: ['UPMC', 'Penn Medicine', 'Geisinger', 'Jefferson Health', 'Temple Health', 'Lehigh Valley Health Network', 'Children\'s Hospital of Philadelphia'],
  },
  {
    slug: 'ohio',
    abbr: 'OH',
    name: 'Ohio',
    metaDescription: 'Free Ohio healthcare jobs — Cleveland, Columbus, Cincinnati. Physician, NP, PA, RN, CRNA roles from Cleveland Clinic, OSU Wexner, Cincinnati Children\'s, more.',
    shortDescription: 'Ohio healthcare openings across Cleveland, Columbus, Cincinnati, Toledo, and Akron.',
    majorMetros: ['Cleveland', 'Columbus', 'Cincinnati', 'Toledo', 'Akron', 'Dayton', 'Youngstown'],
    topEmployers: ['Cleveland Clinic', 'OSU Wexner Medical Center', 'Cincinnati Children\'s', 'University Hospitals (UH Cleveland)', 'OhioHealth', 'Mount Carmel Health', 'Bon Secours Mercy Health'],
  },
  {
    slug: 'georgia',
    abbr: 'GA',
    name: 'Georgia',
    metaDescription: 'Free Georgia healthcare jobs — Atlanta, Savannah, Augusta. Physician, NP, PA, RN, CRNA roles from Emory, Piedmont, Northside, Wellstar, more.',
    shortDescription: 'Georgia healthcare openings across Atlanta metro, Savannah, Augusta, and Macon.',
    majorMetros: ['Atlanta', 'Savannah', 'Augusta', 'Macon', 'Columbus', 'Athens', 'Marietta'],
    topEmployers: ['Emory Healthcare', 'Piedmont Healthcare', 'Northside Hospital', 'Wellstar Health System', 'Children\'s Healthcare of Atlanta', 'Augusta University Health'],
  },
  {
    slug: 'north-carolina',
    abbr: 'NC',
    name: 'North Carolina',
    metaDescription: 'Free North Carolina healthcare jobs — Charlotte, Raleigh, Durham. Physician, NP, PA, RN, CRNA roles from Duke, UNC Health, Atrium, Novant, more.',
    shortDescription: 'North Carolina healthcare openings across the Triangle, Charlotte metro, and Triad.',
    majorMetros: ['Charlotte', 'Raleigh', 'Durham', 'Greensboro', 'Winston-Salem', 'Asheville', 'Wilmington'],
    topEmployers: ['Duke Health', 'UNC Health', 'Atrium Health', 'Novant Health', 'Wake Forest Baptist Health', 'Mission Health', 'Cone Health'],
  },
  {
    slug: 'massachusetts',
    abbr: 'MA',
    name: 'Massachusetts',
    metaDescription: 'Free Massachusetts healthcare jobs — Boston metro + statewide. Physician, NP, PA, RN, CRNA roles from MGH, BWH, Beth Israel, Boston Children\'s, more.',
    shortDescription: 'Massachusetts healthcare openings across Greater Boston, Worcester, and the South Coast.',
    majorMetros: ['Boston', 'Cambridge', 'Worcester', 'Springfield', 'Lowell', 'Quincy'],
    topEmployers: ['Massachusetts General Hospital', 'Brigham and Women\'s Hospital', 'Beth Israel Deaconess', 'Boston Children\'s Hospital', 'Tufts Medical Center', 'Dana-Farber Cancer Institute', 'UMass Memorial Health'],
  },
  {
    slug: 'michigan',
    abbr: 'MI',
    name: 'Michigan',
    metaDescription: 'Free Michigan healthcare jobs — Detroit, Grand Rapids, Ann Arbor. Physician, NP, PA, RN, CRNA roles from Henry Ford, Beaumont, U-M, Spectrum, more.',
    shortDescription: 'Michigan healthcare openings across metro Detroit, Grand Rapids, Ann Arbor, and Lansing.',
    majorMetros: ['Detroit', 'Grand Rapids', 'Ann Arbor', 'Lansing', 'Warren', 'Sterling Heights', 'Flint'],
    topEmployers: ['Henry Ford Health System', 'Beaumont Health', 'University of Michigan Health', 'Spectrum Health (Corewell)', 'Trinity Health Michigan', 'Sparrow Health'],
  },
  {
    slug: 'new-jersey',
    abbr: 'NJ',
    name: 'New Jersey',
    metaDescription: 'Free New Jersey healthcare jobs — Newark, Jersey City, Trenton, Edison. Physician, NP, PA, RN, CRNA roles from RWJBarnabas, Hackensack Meridian, Atlantic Health, more.',
    shortDescription: 'New Jersey healthcare openings across the NYC metro corridor, Trenton, and the Jersey shore.',
    majorMetros: ['Newark', 'Jersey City', 'Trenton', 'Edison', 'Camden', 'Toms River', 'Atlantic City'],
    topEmployers: ['RWJBarnabas Health', 'Hackensack Meridian Health', 'Atlantic Health System', 'Cooper University Health Care', 'Inspira Health', 'Saint Peter\'s Healthcare', 'Virtua Health'],
  },
  {
    slug: 'virginia',
    abbr: 'VA',
    name: 'Virginia',
    metaDescription: 'Free Virginia healthcare jobs — Richmond, Norfolk, Arlington, Charlottesville. Physician, NP, PA, RN, CRNA roles from Inova, Sentara, VCU Health, UVA, more.',
    shortDescription: 'Virginia healthcare openings across Northern VA, Richmond, Hampton Roads, and the Shenandoah Valley.',
    majorMetros: ['Richmond', 'Virginia Beach', 'Norfolk', 'Arlington', 'Alexandria', 'Charlottesville', 'Roanoke'],
    topEmployers: ['Inova Health System', 'Sentara Healthcare', 'VCU Health', 'UVA Health', 'Bon Secours Mercy Health', 'Riverside Health System', 'Carilion Clinic'],
  },
  {
    slug: 'arizona',
    abbr: 'AZ',
    name: 'Arizona',
    metaDescription: 'Free Arizona healthcare jobs — Phoenix, Tucson, Scottsdale. Physician, NP, PA, RN, CRNA roles from Banner Health, HonorHealth, Mayo Clinic Arizona, Dignity, more.',
    shortDescription: 'Arizona healthcare openings across Phoenix metro, Tucson, and the Verde Valley.',
    majorMetros: ['Phoenix', 'Tucson', 'Scottsdale', 'Mesa', 'Chandler', 'Glendale', 'Tempe', 'Flagstaff'],
    topEmployers: ['Banner Health', 'HonorHealth', 'Mayo Clinic Arizona', 'Dignity Health', 'Phoenix Children\'s Hospital', 'Tucson Medical Center', 'Northern Arizona Healthcare'],
  },
  {
    slug: 'washington',
    abbr: 'WA',
    name: 'Washington',
    metaDescription: 'Free Washington healthcare jobs — Seattle, Tacoma, Spokane, Bellevue. Physician, NP, PA, RN, CRNA roles from UW Medicine, Providence, Swedish, MultiCare, more.',
    shortDescription: 'Washington healthcare openings across Seattle metro, Tacoma, Spokane, and the I-5 corridor.',
    majorMetros: ['Seattle', 'Tacoma', 'Spokane', 'Bellevue', 'Vancouver', 'Everett', 'Olympia'],
    topEmployers: ['UW Medicine', 'Providence Swedish', 'Virginia Mason Franciscan Health', 'MultiCare Health System', 'Kaiser Permanente Washington', 'EvergreenHealth', 'Seattle Children\'s'],
  },
  {
    slug: 'tennessee',
    abbr: 'TN',
    name: 'Tennessee',
    metaDescription: 'Free Tennessee healthcare jobs — Nashville, Memphis, Knoxville, Chattanooga. Physician, NP, PA, RN, CRNA roles from Vanderbilt, HCA, Methodist Le Bonheur, Erlanger, more.',
    shortDescription: 'Tennessee healthcare openings across Nashville, Memphis, Knoxville, and the Tri-Cities.',
    majorMetros: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville', 'Murfreesboro', 'Johnson City'],
    topEmployers: ['Vanderbilt Health', 'HCA Healthcare', 'Methodist Le Bonheur Healthcare', 'Erlanger Health System', 'BlueCross BlueShield of Tennessee', 'Ascension Saint Thomas', 'Ballad Health'],
  },
  {
    slug: 'missouri',
    abbr: 'MO',
    name: 'Missouri',
    metaDescription: 'Free Missouri healthcare jobs — Kansas City, St. Louis, Springfield. Physician, NP, PA, RN, CRNA roles from BJC HealthCare, Mercy, SSM Health, CoxHealth, more.',
    shortDescription: 'Missouri healthcare openings across St. Louis, Kansas City, Springfield, and the Ozarks.',
    majorMetros: ['Kansas City', 'St. Louis', 'Springfield', 'Independence', 'Columbia', 'Lee\'s Summit', 'O\'Fallon'],
    topEmployers: ['BJC HealthCare', 'Mercy', 'SSM Health', 'CoxHealth', 'Saint Luke\'s Health System', 'Children\'s Mercy Kansas City', 'Washington University in St. Louis'],
  },
  {
    slug: 'minnesota',
    abbr: 'MN',
    name: 'Minnesota',
    metaDescription: 'Free Minnesota healthcare jobs — Minneapolis, St. Paul, Rochester, Duluth. Physician, NP, PA, RN, CRNA roles from Mayo Clinic, Allina, Fairview, HealthPartners, more.',
    shortDescription: 'Minnesota healthcare openings across the Twin Cities, Rochester (Mayo), and northern Minnesota.',
    majorMetros: ['Minneapolis', 'St. Paul', 'Rochester', 'Duluth', 'Bloomington', 'Brooklyn Park', 'Plymouth'],
    topEmployers: ['Mayo Clinic', 'Allina Health', 'Fairview Health Services', 'HealthPartners', 'Children\'s Minnesota', 'Essentia Health', 'CentraCare'],
  },
  {
    slug: 'wisconsin',
    abbr: 'WI',
    name: 'Wisconsin',
    metaDescription: 'Free Wisconsin healthcare jobs — Milwaukee, Madison, Green Bay. Physician, NP, PA, RN, CRNA roles from Aurora, Froedtert, UW Health, Bellin, ThedaCare, more.',
    shortDescription: 'Wisconsin healthcare openings across Milwaukee, Madison, Green Bay, and the Fox Valley.',
    majorMetros: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine', 'Appleton', 'Eau Claire'],
    topEmployers: ['Advocate Aurora Health', 'Froedtert & MCW', 'UW Health', 'Bellin Health', 'ThedaCare', 'Children\'s Wisconsin', 'Marshfield Clinic Health System'],
  },
  {
    slug: 'colorado',
    abbr: 'CO',
    name: 'Colorado',
    metaDescription: 'Free Colorado healthcare jobs — Denver, Boulder, Colorado Springs. Physician, NP, PA, RN, CRNA roles from UCHealth, Centura, Children\'s Colorado, Kaiser, more.',
    shortDescription: 'Colorado healthcare openings across Denver Front Range, Colorado Springs, Boulder, and the Western Slope.',
    majorMetros: ['Denver', 'Colorado Springs', 'Aurora', 'Boulder', 'Fort Collins', 'Lakewood', 'Pueblo'],
    topEmployers: ['UCHealth', 'Centura Health', 'Children\'s Hospital Colorado', 'Kaiser Permanente Colorado', 'HealthONE', 'Banner Health (Colorado)', 'Denver Health'],
  },
  {
    slug: 'oregon',
    abbr: 'OR',
    name: 'Oregon',
    metaDescription: 'Free Oregon healthcare jobs — Portland, Eugene, Salem, Bend. Physician, NP, PA, RN, CRNA roles from OHSU, Providence, Legacy, Kaiser, Asante, more.',
    shortDescription: 'Oregon healthcare openings across Portland metro, Eugene, Salem, Bend, and southern Oregon.',
    majorMetros: ['Portland', 'Eugene', 'Salem', 'Beaverton', 'Bend', 'Medford', 'Gresham'],
    topEmployers: ['OHSU (Oregon Health & Science University)', 'Providence Health & Services Oregon', 'Legacy Health', 'Kaiser Permanente Northwest', 'Asante', 'PeaceHealth Oregon', 'Salem Health'],
  },
  {
    slug: 'oklahoma',
    abbr: 'OK',
    name: 'Oklahoma',
    metaDescription: 'Free Oklahoma healthcare jobs — Oklahoma City, Tulsa, Norman. Physician, NP, PA, RN, CRNA roles from OU Health, Integris, Saint Francis, Mercy, more.',
    shortDescription: 'Oklahoma healthcare openings across OKC metro, Tulsa, and surrounding rural areas.',
    majorMetros: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond', 'Lawton', 'Stillwater'],
    topEmployers: ['OU Health', 'Integris Health', 'Saint Francis Health System', 'Mercy Hospital Oklahoma City', 'SSM Health Oklahoma', 'Hillcrest HealthCare System', 'Norman Regional Health System'],
  },
  {
    slug: 'kentucky',
    abbr: 'KY',
    name: 'Kentucky',
    metaDescription: 'Free Kentucky healthcare jobs — Louisville, Lexington, Bowling Green. Physician, NP, PA, RN, CRNA roles from UK HealthCare, Norton, Baptist Health, more.',
    shortDescription: 'Kentucky healthcare openings across Louisville, Lexington, and Northern KY (Greater Cincinnati).',
    majorMetros: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington', 'Hopkinsville', 'Frankfort'],
    topEmployers: ['UK HealthCare (University of Kentucky)', 'Norton Healthcare', 'Baptist Health Kentucky', 'St. Elizabeth Healthcare', 'UofL Health', 'CHI Saint Joseph Health', 'Owensboro Health'],
  },
  {
    slug: 'indiana',
    abbr: 'IN',
    name: 'Indiana',
    metaDescription: 'Free Indiana healthcare jobs — Indianapolis, Fort Wayne, Evansville. Physician, NP, PA, RN, CRNA roles from IU Health, Community Health Network, Ascension, more.',
    shortDescription: 'Indiana healthcare openings across Indianapolis metro, Fort Wayne, Evansville, and northwestern Indiana.',
    majorMetros: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel', 'Fishers', 'Bloomington'],
    topEmployers: ['IU Health (Indiana University Health)', 'Community Health Network', 'Ascension St. Vincent', 'Franciscan Health', 'Parkview Health', 'Deaconess Health System', 'Eskenazi Health'],
  },
  {
    slug: 'nevada',
    abbr: 'NV',
    name: 'Nevada',
    metaDescription: 'Free Nevada healthcare jobs — Las Vegas, Henderson, Reno. Physician, NP, PA, RN, CRNA roles from Renown, Sunrise Health, Valley Health System, UHS, more.',
    shortDescription: 'Nevada healthcare openings across Las Vegas, Henderson, Reno, and Carson City.',
    majorMetros: ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks', 'Carson City'],
    topEmployers: ['Renown Health', 'Sunrise Health System', 'Valley Health System', 'Saint Mary\'s (Reno)', 'Northern Nevada Medical Center', 'UMC Southern Nevada', 'Carson Tahoe Health'],
  },
  {
    slug: 'utah',
    abbr: 'UT',
    name: 'Utah',
    metaDescription: 'Free Utah healthcare jobs — Salt Lake City, Provo, Ogden. Physician, NP, PA, RN, CRNA roles from Intermountain, U of Utah Health, MountainStar, Steward, more.',
    shortDescription: 'Utah healthcare openings across the Wasatch Front, St. George, and the Utah valleys.',
    majorMetros: ['Salt Lake City', 'Provo', 'Ogden', 'West Valley City', 'St. George', 'Sandy', 'Orem'],
    topEmployers: ['Intermountain Health', 'University of Utah Health', 'MountainStar Healthcare', 'Steward Health Care', 'Primary Children\'s Hospital', 'Revere Health', 'Ogden Regional Medical Center'],
  },
  {
    slug: 'alabama',
    abbr: 'AL',
    name: 'Alabama',
    metaDescription: 'Free Alabama healthcare jobs — Birmingham, Huntsville, Mobile, Montgomery. Physician, NP, PA, RN, CRNA roles from UAB, Huntsville Hospital, Infirmary Health, more.',
    shortDescription: 'Alabama healthcare openings across Birmingham, Huntsville, Mobile, and Montgomery.',
    majorMetros: ['Birmingham', 'Huntsville', 'Montgomery', 'Mobile', 'Tuscaloosa', 'Hoover', 'Auburn'],
    topEmployers: ['UAB Medicine (University of Alabama at Birmingham)', 'Huntsville Hospital Health System', 'Infirmary Health', 'Children\'s of Alabama', 'Brookwood Baptist Health', 'East Alabama Medical Center', 'DCH Health System'],
  },
  {
    slug: 'arkansas',
    abbr: 'AR',
    name: 'Arkansas',
    metaDescription: 'Free Arkansas healthcare jobs — Little Rock, Fayetteville, Fort Smith. Physician, NP, PA, RN, CRNA roles from UAMS, Baptist Health Arkansas, CHI St. Vincent, more.',
    shortDescription: 'Arkansas healthcare openings across Little Rock, Fayetteville, Fort Smith, and the Delta.',
    majorMetros: ['Little Rock', 'Fayetteville', 'Fort Smith', 'Springdale', 'Jonesboro', 'Rogers', 'Conway'],
    topEmployers: ['UAMS (University of Arkansas for Medical Sciences)', 'Baptist Health Arkansas', 'CHI St. Vincent', 'Mercy Northwest Arkansas', 'Washington Regional Medical Center', 'Arkansas Children\'s Hospital', 'Saline Memorial Hospital'],
  },
]

export function getStateHub(slug: string): StateHub | undefined {
  return STATE_HUBS.find((s) => s.slug === slug)
}
